name: cosnect
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  dropdown_button2: ^2.3.9
  extended_image: ^9.0.7
  # Network
  dio: ^5.7.0
  retrofit: ^4.4.1
  webview_flutter: ^4.10.0
  # Util UI
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.3
  auto_route: ^9.2.2
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  loader_overlay: ^4.0.3
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  flutter_keyboard_visibility: ^6.0.0
  # Util Logic
  intl: ^0.19.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  talker_flutter: ^4.5.2
  talker_dio_logger: ^4.5.2
  talker_riverpod_logger: ^4.5.2
  collection: ^1.18.0
  path: ^1.9.0
  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  supabase_flutter: ^2.8.1
  drift: ^2.22.1
  drift_flutter: ^0.2.2
  # DI, StateManagement
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  # Environment
  envied: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  retrofit_generator: ^9.1.5
  riverpod_generator: ^2.6.3
  envied_generator: ^1.0.0
  mockito: ^5.4.4
  auto_route_generator: ^9.0.0
  json_serializable:
  freezed:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/

  fonts:
    - family: SUITE
      fonts:
        - asset: assets/font/SUITE-Light.otf
          weight: 300
        - asset: assets/font/SUITE-Regular.otf
          weight: 400
        - asset: assets/font/SUITE-Medium.otf
          weight: 500
        - asset: assets/font/SUITE-SemiBold.otf
          weight: 600
        - asset: assets/font/SUITE-Bold.otf
          weight: 700
        - asset: assets/font/SUITE-ExtraBold.otf
          weight: 800

#flutter_native_splash:
#  color: "#38D592"
#  image: assets/images/splash.png
#  fullscreen: true
#  android12: true
#  android_12:
#    color: "#38D592"
#    image: assets/images/splash.png
#    fullscreen: true
flutter_intl:
  enabled: true
